/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Jhonattan
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuGestionConductor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuLicenciasActivas = new javax.swing.JMenuItem();
        mnuLicenciasVencidas = new javax.swing.JMenuItem();
        mnuLicenciasProxVencer = new javax.swing.JMenuItem();
        btnLicencias = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Licencias");

        mnuGestionConductor.setText("Gestion de conductores");
        mnuGestionConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGestionConductorActionPerformed(evt);
            }
        });
        jMenu2.add(mnuGestionConductor);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Reportes");

        mnuLicenciasActivas.setText("Licencias activas");
        mnuLicenciasActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLicenciasActivasActionPerformed(evt);
            }
        });
        jMenu4.add(mnuLicenciasActivas);

        mnuLicenciasVencidas.setText("Licencias vencidas");
        mnuLicenciasVencidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLicenciasVencidasActionPerformed(evt);
            }
        });
        jMenu4.add(mnuLicenciasVencidas);

        mnuLicenciasProxVencer.setText("Licencias proximas a vencer");
        mnuLicenciasProxVencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLicenciasProxVencerActionPerformed(evt);
            }
        });
        jMenu4.add(mnuLicenciasProxVencer);

        btnLicencias.setText("Licencias");
        btnLicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciasActionPerformed(evt);
            }
        });
        jMenu4.add(btnLicencias);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // Boton de salir VPrincipal
        System.exit(0); // Con esto me salgo xd.
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuGestionConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGestionConductorActionPerformed
        //Boton de Gestion VPrincipal
        //Creo un OBJ de tipo vista la que quiero llamar osea Gestion Conductor.
        
        VGetConductores ob = new VGetConductores();
        this.dispose();
        ob.setLocationRelativeTo(null);
        ob.setVisible(true);
    }//GEN-LAST:event_mnuGestionConductorActionPerformed

    private void mnuLicenciasVencidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLicenciasVencidasActionPerformed
        // TODO add your handling code here:
        VLincVencidas ob = new VLincVencidas();
        this.dispose();
        ob.setLocationRelativeTo(null);
        ob.setVisible(true);
    }//GEN-LAST:event_mnuLicenciasVencidasActionPerformed

    private void mnuLicenciasProxVencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLicenciasProxVencerActionPerformed
        // TODO add your handling code here:
        VLincProxVen ob = new VLincProxVen();
        this.dispose();
        ob.setLocationRelativeTo(null);
        ob.setVisible(true);
    }//GEN-LAST:event_mnuLicenciasProxVencerActionPerformed

    private void mnuLicenciasActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLicenciasActivasActionPerformed
        // TODO add your handling code here:
        VLincActivas ob = new VLincActivas();
        this.dispose();
        ob.setLocationRelativeTo(null);
        ob.setVisible(true);
    }//GEN-LAST:event_mnuLicenciasActivasActionPerformed

    private void btnLicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciasActionPerformed
        // TODO add your handling code here:
        VLinc ob = new VLinc();
        this.dispose();
        ob.setLocationRelativeTo(null);
        ob.setVisible(true);
    }//GEN-LAST:event_btnLicenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnLicencias;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mnuGestionConductor;
    private javax.swing.JMenuItem mnuLicenciasActivas;
    private javax.swing.JMenuItem mnuLicenciasProxVencer;
    private javax.swing.JMenuItem mnuLicenciasVencidas;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
