/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.DaoCliente;
import modelo.DaoReportes;
import modelo.DaoSucursal;

/**
 *
 * @author User
 */
public class VReportes extends javax.swing.JPanel {

    /**
     * Creates new form Clientes
     */
    public VReportes() {
        initComponents();
        cargarDatosVentasDia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        btnVentasDia = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        JScrollPane1 = new javax.swing.JScrollPane();
        tblReportes = new javax.swing.JTable();
        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnVentasAnio = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(740, 510));

        background.setBackground(new java.awt.Color(229, 229, 229));
        background.setMinimumSize(new java.awt.Dimension(0, 0));
        background.setPreferredSize(new java.awt.Dimension(740, 520));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentasDia.setBackground(new java.awt.Color(21, 25, 29));
        btnVentasDia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentasDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasDiaMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SlimSansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ventas por dia");

        javax.swing.GroupLayout btnVentasDiaLayout = new javax.swing.GroupLayout(btnVentasDia);
        btnVentasDia.setLayout(btnVentasDiaLayout);
        btnVentasDiaLayout.setHorizontalGroup(
            btnVentasDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVentasDiaLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(17, 17, 17))
        );
        btnVentasDiaLayout.setVerticalGroup(
            btnVentasDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        background.add(btnVentasDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        tblReportes.setFont(new java.awt.Font("SlimSansSerif", 0, 12)); // NOI18N
        tblReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sucursal", "Vendedor", "Monto de ventas"
            }
        ));
        JScrollPane1.setViewportView(tblReportes);

        background.add(JScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 700, 310));

        top.setBackground(new java.awt.Color(21, 25, 29));
        top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SlimSansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reportes");
        top.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 740, 40));

        background.add(top, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 750, 60));

        search.setBackground(new java.awt.Color(33, 37, 41));
        search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscar.setText("Ingrese la identificacion");
        txtBuscar.setBorder(null);
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });
        search.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 210, 20));

        btnBuscar.setBackground(new java.awt.Color(21, 25, 29));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SlimSansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Buscar");

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        search.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 80, 20));

        background.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 59, 750, 60));

        btnVentasAnio.setBackground(new java.awt.Color(21, 25, 29));
        btnVentasAnio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentasAnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasAnioMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("SlimSansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Ventas por año");

        javax.swing.GroupLayout btnVentasAnioLayout = new javax.swing.GroupLayout(btnVentasAnio);
        btnVentasAnio.setLayout(btnVentasAnioLayout);
        btnVentasAnioLayout.setHorizontalGroup(
            btnVentasAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVentasAnioLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(17, 17, 17))
        );
        btnVentasAnioLayout.setVerticalGroup(
            btnVentasAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        background.add(btnVentasAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        cargarDatosVentasAnio(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnVentasDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasDiaMouseClicked
        cargarDatosVentasDia();
    }//GEN-LAST:event_btnVentasDiaMouseClicked

    private void btnVentasAnioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasAnioMouseClicked
        txtBuscar.setText("Ingrese el año de busqueda");
        cargarDatosVentasAnio(""+LocalDate.now().getYear());
    }//GEN-LAST:event_btnVentasAnioMouseClicked

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        txtBuscar.setText(null);
        txtBuscar.setForeground(Color.black);
    }//GEN-LAST:event_txtBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnVentasAnio;
    private javax.swing.JPanel btnVentasDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel search;
    private javax.swing.JTable tblReportes;
    private javax.swing.JPanel top;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosVentasDia() {
        DaoReportes daoReportes = new DaoReportes();
        ResultSet ventasDia = daoReportes.getVentasDia();
        int size, i = 0;
        try {
            if (ventasDia != null) {
                // Obtiene el tamaño del ResultSet (Numero de registros).
                ventasDia.last(); // Mueve el puntero al ultimo dato
                size = ventasDia.getRow(); // Obtiene el numero de la fila
                ventasDia.beforeFirst(); // Se mueve al inicio
                
                DefaultTableModel tableModel = new DefaultTableModel(new String []{"Sucursal", "Vendedor", "Monto de la venta"}, size);
                tblReportes.setModel(tableModel);
                
                //Recorrido de datos...
                while (ventasDia.next()) {
                    tableModel.setValueAt(ventasDia.getString("sucursal"), i, 0);
                    tableModel.setValueAt(ventasDia.getString("nombre") + " " + ventasDia.getString("apellido"), i, 1);
                    tableModel.setValueAt(ventasDia.getString("monto"), i, 2);
                    i++;
                }
            } else {
                JOptionPane.showMessageDialog(this, "No existen registros en la base de datos");
            }
        } catch (SQLException ex) {
            System.out.println("Error: No se pudo consultar la lista de clientes: "+ ex);
        }
    }

    private void cargarDatosVentasAnio(String filtro) {
        DaoReportes daoReportes = new DaoReportes();
        ResultSet ventasAnio = daoReportes.getVentasAnio(filtro);
        int size, i = 0;
        try {
            if (ventasAnio != null) {
                // Obtiene el tamaño del ResultSet (Numero de registros).
                ventasAnio.last(); // Mueve el puntero al ultimo dato
                size = ventasAnio.getRow(); // Obtiene el numero de la fila
                ventasAnio.beforeFirst(); // Se mueve al inicio
                
                DefaultTableModel tableModel = new DefaultTableModel(new String []{"Sucursal", "Vendedor", "Monto de la venta"}, size);
                tblReportes.setModel(tableModel);
                
                //Recorrido de datos...
                while (ventasAnio.next()) {
                    tableModel.setValueAt(ventasAnio.getString("sucursal"), i, 0);
                    tableModel.setValueAt(ventasAnio.getString("fecha"), i, 1);
                    tableModel.setValueAt(ventasAnio.getString("monto"), i, 2);
                    i++;
                }
            }
        } catch (SQLException ex) {
            System.out.println("Error: No se pudo consultar la lista de clientes: "+ ex);
        }
    }
}
